package com.bnfix.ubm.domains.employee;
import com.bnfix.ubm.domains.account.*; import com.bnfix.ubm.domains.company.*; import com.bnfix.ubm.domains.employee.dto.*; import com.bnfix.ubm.domains.manager.*; import com.bnfix.ubm.domains.shared.domain.CPF; import com.bnfix.ubm.domains.shared.enums.Role; import com.bnfix.ubm.domains.redemption.RedemptionTokenRepository; import com.bnfix.ubm.domains.subscription.CompanyBenefitAssignmentService; import com.bnfix.ubm.shared.security.TenantGuard; import jakarta.transaction.Transactional; import java.util.List; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.web.server.ResponseStatusException;
@Service public class EmployeeService {
  private final AccountRepository accounts; private final CompanyRepository companies; private final ManagerRepository managers; private final EmployeeRepository employees; private final TenantGuard tenant; private final RedemptionTokenRepository tokens; private final BCryptPasswordEncoder passwords; private final CompanyBenefitAssignmentService assignments;
  public EmployeeService(AccountRepository a,CompanyRepository c,ManagerRepository m,EmployeeRepository e,TenantGuard t,RedemptionTokenRepository rt,BCryptPasswordEncoder p,CompanyBenefitAssignmentService as){accounts=a;companies=c;managers=m;employees=e;tenant=t;tokens=rt;passwords=p;assignments=as;}
  @Transactional public EmployeeResponse create(CreateEmployeeRequest r,String email,Long tenantId){if(accounts.findByEmail(r.email()).isPresent())throw conflict("Email already in use");if(accounts.findByCPF(r.cpf()).isPresent())throw conflict("CPF already in use");Manager m=manager(email,tenantId);Company c=tenant.verifyManagerCompanyAccess(m,r.companyId());Account a=accounts.save(Account.builder(r.name(),CPF.of(r.cpf()),passwords.encode(r.password()),r.email(),Role.USER).build());Employee employee=employees.save(Employee.builder(r.name(),c,a).build());assignments.assignActiveCompanyBenefits(employee);return response(employee);}
 @Transactional public EmployeeResponse disable(Long id,String email,Long company){Manager m=manager(email,company);Employee e=tenant.verifyManagerEmployeeAccess(m,find(id));e.disable();tokens.revokeActiveByEmployee(e.id);return response(e);}
 @Transactional public EmployeeResponse activate(Long id,String email,Long company){Manager m=manager(email,company);Employee e=tenant.verifyManagerEmployeeAccess(m,find(id));e.active();return response(e);}
 @Transactional public EmployeeResponse update(Long id,UpdateEmployeeRequest r,String email,Long company){Employee e=tenant.verifyManagerEmployeeAccess(manager(email,company),find(id));e.update(r.name());return response(e);}
 @Transactional public List<EmployeeResponse> list(String email,Long company,int page,int size){Company c=tenant.verifyManagerCompanyAccess(manager(email,company),company);return employees.findByCompanyId(c.id,Math.max(0,page),Math.max(1,Math.min(size,100))).stream().map(this::response).toList();}
 private Manager manager(String e,Long c){return managers.findByEmailAndCompanyId(e,c).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Manager not Found"));} private Employee find(Long id){return employees.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Employee not Found"));} private EmployeeResponse response(Employee e){return new EmployeeResponse(e.id,e.getName(),e.getCompany().id,e.getActive(),e.getCreatedAt());} private ResponseStatusException conflict(String s){return new ResponseStatusException(HttpStatus.CONFLICT,s);}
}
