quarkus:
  datasource:
    db-kind: postgresql

  smallrye-jwt:
    enabled: true

  swagger-ui:
    always-include: true

  rate-limiter:
    buckets:
      auth-group:
        limits:
          - permitted-uses: ${AUTH_RATE_LIMIT_USES_SECOND}
            period: ${AUTH_RATE_LIMIT_PERIOD_SECOND_}
          - permitted-uses: ${AUTH_RATE_LIMIT_USES_MINUTE}
            period: ${AUTH_RATE_LIMIT_PERIOD_MINUTE}
      onboarding-group:
        limits:
          - permitted-uses: ${ONBOARDING_RATE_LIMIT_USES_SECOND}
            period: ${ONBOARDING_RATE_LIMIT_PERIOD_SECOND_}
          - permitted-uses: ${ONBOARDING_RATE_LIMIT_USES_MINUTE}
            period: ${ONBOARDING_RATE_LIMIT_PERIOD_MINUTE}
mp:
  jwt:
    token:
      header: Cookie
      cookie: jwt
    verify:
      publickey:
        location: /opt/bn/secrets/publicKey.pem
      issuer: bn-api

app:
  cookie:
    secure: true
  swagger:
    auth:
      username: ${SWAGGER_BASIC_AUTH_USERNAME:}
      password: ${SWAGGER_BASIC_AUTH_PASSWORD:}


smallrye:
  jwt:
    sign:
      key:
        location: /opt/bn/secrets/privateKey.pem

"%prod":
  quarkus:
    http:
      auth:
        basic: true
        permission:
          docs:
            paths: /q/swagger-ui/*,/q/openapi*
            policy: authenticated
