spring:
  application:
    name: benefix
  datasource:
    url: jdbc:postgresql://localhost:5432/benefix
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

springdoc:
  swagger-ui:
    path: /docs