quarkus:
  datasource:
    db-kind: postgresql
    reactive:
      trust-certificates-pem: /certs/global-bundle.pem
      hostname-verification-algorithm: HTTPS
      postgresql:
        ssl-mode: verify-full
  smallrye-jwt:
    enabled: true

mp:
  jwt:
    token:
      header: Cookie
      cookie: jwt
    verify:
      publickey:
        location: /opt/bn/secrets/publicKey.pem
      issuer: bn-api

app:
  cookie:
    secure: true
  swagger:
    auth:
      username: ${SWAGGER_BASIC_AUTH_USERNAME:}
      password: ${SWAGGER_BASIC_AUTH_PASSWORD:}


smallrye:
  jwt:
    sign:
      key:
        location: /opt/bn/secrets/privateKey.pem

  swagger-ui:
    always-include: true

"%prod":
  quarkus:
    http:
      auth:
        basic: true
        permission:
          docs:
            paths: /q/swagger-ui/*,/q/openapi*
            policy: authenticated
