package com.bnfix.ubm.domains.benefit;
import com.bnfix.ubm.domains.category.*; import com.bnfix.ubm.domains.category.dto.CategoryResponse; import com.bnfix.ubm.domains.company.*; import com.bnfix.ubm.domains.manager.*; import com.bnfix.ubm.domains.benefit.dto.*; import com.bnfix.ubm.domains.subscription.CompanyBenefitAssignmentService; import com.bnfix.ubm.shared.security.TenantGuard; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service public class BenefitService { private final BenefitRepository benefits; private final CompanyRepository companies; private final CategoryRepository categories; private final ManagerRepository managers; private final TenantGuard tenant; private final CompanyBenefitAssignmentService assignments;
 public BenefitService(BenefitRepository b,CompanyRepository c,CategoryRepository ca,ManagerRepository m,TenantGuard t,CompanyBenefitAssignmentService a){benefits=b;companies=c;categories=ca;managers=m;tenant=t;assignments=a;}
 @Transactional public BenefitResponse create(CreateBenefitRequest r,String email,Long tenantId){Manager m=manager(email,tenantId);Company c=tenant.verifyManagerCompanyAccess(m,r.companyId());Set<Category> cs=fetch(r.categoryIds());return response(benefits.save(Benefit.builder(r.name(),c).description(r.description()).categories(cs).availability(r.publiclyVisible(),r.validFrom(),r.validUntil(),r.maxUsesPerUser(),r.terms()).build()));}
 @Transactional(readOnly=true) public Page<BenefitResponse> tenant(String email,Long id,Long categoryId,int page,int size){manager(email,id);Pageable p=PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100));return (categoryId==null?benefits.findByCompanyId(id,p):benefits.findByCompanyIdAndCategoryId(id,categoryId,p)).map(this::response);}
 @Transactional(readOnly=true) public Page<BenefitResponse> marketplace(String email,Long id,Long categoryId,int page,int size){manager(email,id);Pageable p=PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100));return (categoryId==null?benefits.findPublicAvailableByProviderNot(id,p):benefits.findActiveByProviderNotAndCategoryId(id,categoryId,p)).map(this::response);}
 @Transactional public BenefitResponse update(Long benefitId,UpdateBenefitRequest r,String email,Long id){Manager m=manager(email,id);Benefit b=benefit(benefitId);tenant.verifyManagerCompanyAccess(m,b.getProvider().id);b.update(r.name(),r.description());b.updateAvailability(r.publiclyVisible(),r.validFrom(),r.validUntil(),r.maxUsesPerUser(),r.terms());if(r.categoryIds()!=null)b.updateCategories(fetch(r.categoryIds()));return response(b);}
 @Transactional public BenefitResponse status(Long benefitId,String email,Long id,boolean active){Manager m=manager(email,id);Benefit b=benefit(benefitId);tenant.verifyManagerCompanyAccess(m,b.getProvider().id);if(active){b.activeBenefit();assignments.assignBenefitToActiveEmployees(b);}else b.deactivateBenefit();return response(b);}
 @Transactional public void delete(Long benefitId,String email,Long id){Manager m=manager(email,id);Benefit b=benefit(benefitId);tenant.verifyManagerCompanyAccess(m,b.getProvider().id);benefits.delete(b);}
 private Manager manager(String e,Long id){return managers.findByEmailAndCompanyId(e,id).map(com.bnfix.ubm.shared.security.AccessStatusGuard::requireActive).orElseThrow(()->new NoSuchElementException("Manager not found"));} private Benefit benefit(Long id){return benefits.findByIdWithProviderAndCategories(id).orElseThrow(()->new NoSuchElementException("Benefit not found"));} private Set<Category> fetch(List<Long> ids){if(ids==null||ids.isEmpty())return Set.of();List<Category> found=categories.findAllById(ids);if(found.size()!=new HashSet<>(ids).size())throw new NoSuchElementException("One or more categories not found");return Set.copyOf(found);} private BenefitResponse response(Benefit b){return new BenefitResponse(b.id,b.getName(),b.getDescription(),b.getProvider().getName(),b.getActive(),b.getPubliclyVisible(),b.getValidUntil(),b.getMaxUsesPerUser(),b.getTerms(),b.getCreatedAt(),b.getCategories().stream().map(c->new CategoryResponse(c.id,c.getName())).toList());} }
